version: '2.4'

services:
    postgres:
        container_name: go_todo_postgres
        image: postgres:13.3-alpine
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - "todo_list:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: "secret"
        networks:
            - todo_list

    backend:
        container_name: go_todo_backend
        build: .
        depends_on: 
            - postgres
        ports:
            - "3000:3000"
        networks: 
            - todo_list

volumes:
    todo_list:

networks:
    todo_list: