// Code generated by sqlc. DO NOT EDIT.

package postgres

import (
	"time"
)

type Todo struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Complete  bool      `json:"complete"`
	CreatedAt time.Time `json:"createdAt"`
}
