### hello world
GET http://localhost:3000/


### Get all todos
GET http://localhost:3000/api/todos

### Add new todo
POST http://localhost:3000/api/todos HTTP/1.1
content-type: application/json

{
    "name": "GG1"
}